name: currency_exchange
description: Currency Exchange Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.19.4 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    # Caches images to reduce waste
    cached_network_image: ^3.2.3

    # Functions that operate on lists and collections
    collection: ^1.17.1

    # Simplifies Equality Comparisons
    equatable: ^2.0.5

    # Used to make HTTP requests
    dio: ^5.1.2

    # Dependency Injection service locator
    get_it: ^7.6.0

    # Dependency Injection service locator
    injectable: ^2.1.1

    # Bloc state management for separation from user interface
    flutter_bloc: ^8.1.2

    # Providers needed providing blocs
    provider: ^6.0.5

    # Hooks to support state management (animations and form validation)
    flutter_hooks: ^0.18.6

    # Storage of global environment variables
    flutter_dotenv: ^5.0.2

    # flutter charts for data visualization in dart
    syncfusion_flutter_charts: ^21.2.4

    # Hive is a lightweight and fast NoSQL database for storing data locally on the device.
    hive: ^2.2.3
    # hive_flutter is a plugin that provides integration between Hive and Flutter.
    hive_flutter: ^1.1.0

    # Path_provider is a plugin that provides a platform-specific (Android/iOS) way to access the device's file system.
    path_provider: ^2.0.15

    # Functional error handling in flutter
    dartz: ^0.10.1

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.5

dev_dependencies:
    flutter_test:
        sdk: flutter
    # Flutter Lints is a static analysis tool that highlights potential issues and style violations.
    lint: ^2.1.2

    # Hive Generator is a generator for Hive.
    hive_generator: ^2.0.0

    # Injectable Generator is a generator for injectable.
    injectable_generator: ^2.1.5

    # Mocktail is a Dart package for creating mocks and stubs.
    mocktail: ^0.3.0

    # Bloc Test is a package that provides utilities for testing blocs and cubits.
    bloc_test: ^9.1.1

    # Build Runner is a package that provides a concrete way of generating files using Dart code, outside of tools like pub and the Dart VM.
    build_runner: ^2.4.4

flutter:
    uses-material-design: true
    assets:
        - keys.env
